### ISSUE TITLE
Optimizing PNGs

### ISSUE THREAD

**Issue by C0rn3j** [felixmde/ptoos-xray#5]
`oxipng -o max ./*.png` shaves off about 100KB off the final filesize. Arguably it is not THAT much, but it is an improvement.

Looks like there's a Python wrapper for it too https://pypi.org/project/pyoxipng/

If you choose to implement it, having it toggle-able may be a good idea as throwing 20MB of PNGs at it may chug on older low-end devices.

**Comment by felixmde** [comment]
Thanks for the suggestion!

I played around with different compression programs and got the best results with [pngquant](https://pngquant.org/). I don't think the lossy compression matters on eBook readers and it reduced the size from 21MB to 9.3MB.

I will probably put the compressed PNGs into this repository (should be okay as long as I credit Bulbapedia). It doesn't make sense that everyone who just wants to patch their epub has to download all the data from Bulbapedia.

Does that make sense?

**Comment by C0rn3j** [comment]
I haven't even thought of lossy compression, I suppose it definitely makes sense and has some real file savings.

Don't think the one-time 21MB~ load on Bulbapedia is relevant as just loading the main page in the browser is 7MB.

Sounds good
